---
title: "Palmetto binary logistic regression"
author: "Laurel Wee"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(ggfortify)
library(patchwork)
```
```{r, message=FALSE, warning=FALSE}
palmetto <- read_csv(here("data","palmetto.csv")) %>% 
  mutate(species_full = case_when(
    species %in% "1"~"Serenoa repens",
    species %in% "2"~"Sabal etonia"))
  
```
### Part 1 
```{r, part_i}
#Make a subset of data including heigh, canopy length, canopy width, and green leaves for species Serenoa repens and Sabal etonia

classify_palmetto <- palmetto %>% 
  select(height, length, width, green_lvs, species_full) %>% 
  drop_na() %>% 
  mutate(species_full = factor(species_full))
```


```{r}
plot1 <- ggplot(classify_palmetto, aes(x = height, y = length, color= species_full)) +
  geom_point() +
  facet_wrap(~species_full)+
  theme(legend.position = "none")

plot2 <- ggplot(classify_palmetto, aes(x = height, y = green_lvs, color= species_full)) +
  geom_point() +
  facet_wrap(~species_full)+
  theme(legend.position = "none")

```


```{r}
palmetto_pca <- classify_palmetto %>% 
  select(green_lvs,height, length, width) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp()

pca_plot <- autoplot(palmetto_pca, 
         data = classify_palmetto, 
         colour='species_full', 
         loadings=TRUE,
         loadings.colour= 'black', 
         loadings.label= TRUE,
         loadings.label.colour= 'black')+
  theme(legend.title = element_blank())

combined_plot <- (plot1|plot2)/pca_plot
combined_plot
```
### Part 2

```{r, part_ii}
palmetto_blr <- glm(species_full ~ height+length+width+green_lvs,
                    data = classify_palmetto,
                    family = "binomial")
palmetto_blr
summary(palmetto_blr)
palmetto_blr_tidy <- broom::tidy(palmetto_blr)
palmetto_blr_tidy


```
### Part 3
```{r}
palmetto_blr_fitted <- palmetto_blr %>% 
  broom::augment(type.predict = "response") %>% 
  select(species_full, .fitted) %>% 
  mutate(predicted = case_when(.fitted >= .50 ~ "	
Serenoa repens",.fitted <.50 ~ "Sabal etonia")) %>% 
  mutate(correct = case_when(species_full == predicted ~ "yes", TRUE ~"no"))

palmetto_blr_correct <- palmetto_blr_fitted %>% 
  pivot_wider(names_from = species_full,values_from = predicted) 
```

### Data source: 

Abrahamson, W.G. 2019. Survival, growth and biomass estimates of two dominant palmetto species of south-central Florida from 1981 - 2017, ongoing at 5-year intervals ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/f2f96ec76fbbd4b9db431c79a770c4d5

